# Generated by Django 6.0.2 on 2026-05-18 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dia_da_semana', models.CharField(max_length=20)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(default=3)),
                ('repeticoes', models.CharField(max_length=20)),
                ('carga_atual_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='treino.exerciciocatalogo')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='treino.treino')),
            ],
        ),
    ]
