# Generated by Django 6.0.2 on 2026-05-18 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treino', '0002_remove_treino_aluno_alter_itemtreino_carga_atual_kg_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_kg', models.DecimalField(decimal_places=1, max_digits=5)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_cargas', to=settings.AUTH_USER_MODEL)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treino.exerciciocatalogo')),
            ],
            options={
                'ordering': ['-data_registro'],
            },
        ),
    ]
